package by.epam.javatraining.beseda.webproject.model.dao.entitydao;

import by.epam.javatraining.beseda.webproject.model.entity.car.Bus;
import by.epam.javatraining.beseda.webproject.model.entity.car.Car;
import by.epam.javatraining.beseda.webproject.model.entity.car.Truck;
import by.epam.javatraining.beseda.webproject.model.exception.DAOexception.CarTypeNotPresentException;
import by.epam.javatraining.beseda.webproject.model.exception.DAOexception.DAOLayerException;
import by.epam.javatraining.beseda.webproject.model.exception.DAOexception.DAOTechnicalException;
import by.epam.javatraining.beseda.webproject.util.resourceloader.DatabaseEnumLoader;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import static by.epam.javatraining.beseda.webproject.util.database.DBEntityTableName.*;
import static by.epam.javatraining.beseda.webproject.util.database.DBEnumTable.*;
import static by.epam.javatraining.beseda.webproject.util.database.SQLQuery.*;

public class CarDAO extends AbstractDAO<Car> {

    private static CarDAO instance = null;

    private CarDAO() {
        super();
    }

    public static CarDAO getDAO() {
        if (instance == null) {
            instance = new CarDAO();
        }
        return instance;
    }

    @Override
    protected Car createEntity(ResultSet result) throws CarTypeNotPresentException, SQLException {
        String carType = result.getString(CAR_TYPE);
        Car car;
        if (carType == BUS) {
            car = new Bus();
            ((Bus) car).setSeats(result.getInt(SEATS_NUMBER));
        } else if (carType == TRUCK) {
            car = new Truck();
            ((Truck) car).setCapacity(result.getInt(TRUCK_CAPACITY));
        } else {
            throw new CarTypeNotPresentException();
        }
        car.setId(result.getInt(CAR_ID));
        car.setModel(result.getString(MODEL));
        car.setNumber(result.getString(CAR_NUMBER));
        car.setState(result.getString(CAR_STATE));
        car.setStatus(result.getString(CAR_STATUS));
        return car;
    }

    @Override
    public int add(Car car) throws DAOLayerException {
        PreparedStatement st = null;
        int id = -1;
        try {
            if (car instanceof Truck) {
                addTruck(st, (Truck) car);
            } else if (car instanceof Bus) {
                addBus(st, (Bus) car);
            } else {
                throw new CarTypeNotPresentException();
            }
            st.executeUpdate();
            ResultSet res = st.getGeneratedKeys();
            id = res.getInt(1);
        } catch (SQLException e) {
            throw new DAOTechnicalException("Error updating database", e);
        } finally {
            closeStatement(st);
        }
        return id;
    }

    private void addBus(PreparedStatement st, Bus car) throws SQLException {
        st = connector.prepareStatementWithAutoGeneratedKeys(ADD_NEW_BUS);
        int carTypeIndex = DatabaseEnumLoader.CAR_TYPE_MAP.getKey(BUS);
        st.setInt(1, carTypeIndex);
        setDataOnPreparedStatement(st, car);
    }

    private void addTruck(PreparedStatement st, Truck car) throws SQLException {
        st = connector.prepareStatementWithAutoGeneratedKeys(ADD_NEW_TRUCK);
        int carTypeIndex = DatabaseEnumLoader.CAR_TYPE_MAP.getKey(TRUCK);
        st.setInt(1, carTypeIndex);
        setDataOnPreparedStatement(st, car);
    }

    @Override
    public void update(Car car) throws DAOLayerException {
        PreparedStatement st = null;
        try {
            if (car instanceof Truck) {
                updateTruck(st, (Truck) car);
            } else if (car instanceof Bus) {
                updateBus(st, (Bus) car);
            } else {
                throw new CarTypeNotPresentException();
            }
            st.setInt(updateIdParameterNumber(), car.getId());
            st.executeUpdate();
        } catch (SQLException e) {
            throw new DAOTechnicalException("Error updating database", e);
        } finally {
            closeStatement(st);
        }
    }

    private void updateTruck(PreparedStatement st, Truck car) throws SQLException {
        st = connector.prepareStatement(UPDATE_TRUCK);
        String truckCapacity = car.getCapacity() + "";
        int truckCapacityIndex = DatabaseEnumLoader.TRUCK_CAPACITY_MAP.getKey(truckCapacity);
        st.setInt(2, truckCapacityIndex);
        setDataOnPreparedStatement(st, car);
    }

    private void updateBus(PreparedStatement st, Bus car) throws SQLException {
        st = connector.prepareStatement(UPDATE_BUS);
        st.setInt(2, car.getSeats());
        setDataOnPreparedStatement(st, car);
    }

    @Override
    protected String getAllStatement() {
        return SELECT_ALL_CARS;
    }

    @Override
    protected String findEntityByIdStatement() {
        return SELECT_CAR_BY_ID;
    }

    /**
     * Undefined
     * @return null
     */
    @Override
    protected String addStatement() {
        return null;
    }

    @Override
    protected String deleteStatement() {
        return DELETE_CAR_BY_ID;
    }


    /**
     * Undefined
     * @return null
     */
    @Override
    protected String updateStatement() {
        return null;
    }

    @Override
    protected int updateIdParameterNumber() {
        return 7;
    }

    @Override
    protected void setDataOnPreparedStatement(PreparedStatement st, Car car) throws SQLException {
        int carStateIndex = DatabaseEnumLoader.CAR_STATE_MAP.getKey(car.getState());
        int carStatusIndex = DatabaseEnumLoader.CAR_STATUS_MAP.getKey(car.getStatus());
        st.setString(3, car.getNumber());
        st.setString(4, car.getModel());
        st.setInt(5, carStatusIndex);
        st.setInt(6, carStateIndex);
    }

}
