package by.epam.javatraining.beseda.webproject.dao.util.wrapperconnector;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public interface ConnectionWrap {

	public Statement createStatement() throws SQLException;

	public PreparedStatement prepareStatement(String statement) throws SQLException;

	public PreparedStatement prepareStatementWithAutoGeneratedKeys(String statement) throws SQLException;

	public void closeStatement(Statement st);

	public void closeConnector();

}
