package by.epam.javatraining.beseda.webproject.model.command;

public enum ActionCommandName {
    LOGIN,
    LOGOUT,
    CUSTOMER_REGISTER,

    CHANGE_LOCALE,

    LOGIN_PAGE,
    CUSTOMER_REGISTER_PAGE,
    PERSONAL_CUSTOMER_DATA_PAGE,
    CUSTOMER_MAIN_PAGE,

    CHANGE_ROUTE_STATUS,
    CHANGE_CAR_STATE,
    CHANGE_ROUTE_STATUS_CAR_STATE,
    CHANGE_CUSTOMER_PASSWORD,
    CHANGE_CUSTOMER_DATA,
    ADD_REQUEST,
    UPDATE_CUSTOMER_REQUEST_LIST,

    DELETE_REQUEST
}
