package by.epam.javatraining.beseda.webproject.util.wrapperconnector;

import by.epam.javatraining.beseda.webproject.util.connectionpool.DBConnector;
import org.apache.log4j.Logger;

import static by.epam.javatraining.beseda.webproject.util.database.SQLQuery.SEMICOLON;
import static by.epam.javatraining.beseda.webproject.util.resourceloader.DatabaseProperties.DATABASE_URL;
import static by.epam.javatraining.beseda.webproject.util.resourceloader.DatabaseProperties.DATABASE_USER;
import static by.epam.javatraining.beseda.webproject.util.resourceloader.DatabaseProperties.DATABASE_PASSWORD;
import static by.epam.javatraining.beseda.webproject.util.resourceloader.GeneralProperties.WAIT_FOR_DB_RESPONSE;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class WrapperConnector {

    private static Logger log = Logger.getLogger("error");

    private Connection connection;
    private static DBConnector pool;

    public WrapperConnector() {
        pool = DBConnector.createConnectionPool(DATABASE_URL, DATABASE_USER, DATABASE_PASSWORD);
        try {
            connection = pool.getConnection();
        } catch (SQLException e) {
            log.error("Error creating a connection to database: " + e);
        }
    }

    public Statement createStatement() throws SQLException {
        validateConnection();
        return connection.createStatement();
    }

    public PreparedStatement prepareStatement(String statement) throws SQLException {
        validateConnection();
        return connection.prepareStatement(statement + SEMICOLON);
    }

    public PreparedStatement prepareStatementWithAutoGeneratedKeys(String statement) throws SQLException {
        validateConnection();
        return connection.prepareStatement(statement + SEMICOLON, Statement.RETURN_GENERATED_KEYS);
    }

    public void closeStatement(Statement st) {
        if (st != null) {
            try {
                st.close();
            } catch (SQLException e) {
                log.error("Error closing statement: " + e);
            }
        }
    }

    public void closeConnector() {
        if (connection != null) {
            pool.releaseConnection(connection);
        }
    }

    private void validateConnection() throws SQLException{
        if (connection == null
                || (!connection.isValid(WAIT_FOR_DB_RESPONSE))) {
            connection = pool.getConnection();
        }
    }
}
